function IM_plot_statitics(datos_procesados, nodo, variable, direccion_variable, month_names, seasons, season_label, graf, nombre, save_dir_fig, opts)
%IM_plot_statitics Genera gráficos estadísticos mensuales y estacionales.
%
% La función genera, para una variable seleccionada, boxplot mensual, PDF
% mensual, CDF mensual, rosa mensual y gráficos estacionales.

%% Manejo de entradas

arguments
    datos_procesados 
    nodo 
    variable 
    direccion_variable 
    month_names 
    seasons 
    season_label 
    graf 
    nombre 
    save_dir_fig 

    opts.do_boxplot logical = true
    opts.do_pdf_mensual logical = true
    opts.do_cdf_mensual logical = true
    opts.do_rose_mensual logical = true
    opts.do_estacional logical = true
    opts.disp_info logical = true
end

variable = char(variable);
direccion_variable = char(direccion_variable);
unidad = graf.(variable).unidad;

if isfield(graf.(variable).pdf, 'nbins')
    nbins_pdf = graf.(variable).pdf.('nbins');
else
    nbins_pdf = 50;
end

%% Grafico de cajas y bigotes mensual

if opts.do_boxplot

    nombre_fig = ['Cajas_meses_', char(variable)];
    meses = [];
    var_box = [];

    for m = 1:12
        mes = get_month_name(month_names, m);                       %Extraer mes
        datos_mes = datos_procesados.params(nodo).(variable).(mes); %Extraer datos de mes.
        datos_mes = clean_vector(datos_mes);                        %Limpiar datos si incluyeran Inf o NaN.
        
        % Si existen datos en el mes, entonces concatenarlos en matrices.
        if ~isempty(datos_mes)
            var_box = [var_box; datos_mes]; %#ok<AGROW>
            meses = [meses; m*ones(numel(datos_mes),1)]; %#ok<AGROW>
        end
    end
    
    % Imprimir mensaje de skip en caso de que datos esten vacios
    if isempty(var_box)
        print_skip(opts.disp_info, 'Boxplot mensual', variable, 'sin datos válidos');
    else
    
        IM_plot_box_mensual(var_box, ...
                            meses, ...
                            'name', [nombre_fig, nombre], ...
                            'save_dir', save_dir_fig, ...
                            'Ylabel', graf.(variable).box.ylabel, ...
                            'ColorCaja', graf.(variable).box.ColorCaja, ...
                            'MedianColor', graf.(variable).box.MedianColor, ...
                            'Whisker', graf.(variable).box.Whisker, ...
                            'Symbol', graf.(variable).box.Symbol, ...
                            'Widths', graf.(variable).box.Widths, ...
                            'ShowMedianLine', graf.(variable).box.ShowMedianLine, ...
                            'Limy', graf.(variable).box.Limy);
    end
end

%% Funciones de densidad de probabilidad mensuales

if opts.do_pdf_mensual
    nombre_fig = ['PDF_mensual_', char(variable), '_'];

    
    for m = 1:12

        mes = get_month_name(month_names, m);                       %Extraer mes
        var = datos_procesados.params(nodo).(variable).(mes);       %Extraer datos de mes.
        var = clean_vector(var);

        % Imprimir mensaje de skip en caso de que datos esten vacios
        if isempty(var)
            print_skip(opts.disp_info, 'PDF mensual', variable, mes);
            continue

        else
            N_fig = [[nombre_fig, nombre], mes];
            Etiq_x = [char(variable), ' (', char(unidad), ')'];
            Etiq_y = 'Densidad de probabilidad';
               
            Text = stat_text_pdf(var, ...
                            unidad, ...
                            graf.(variable).pdf.TextX, ...
                            graf.(variable).pdf.TextY, ...
                            graf.(variable).pdf.TextStep, ...
                            graf.(variable).pdf.TextSize);

            IM_plot_histogram(var, ...
                "Name", N_fig, ...
                "titulo", "", ...
                "ext", graf.general.ext, ...
                "save_dir", save_dir_fig, ...
                "dpi", graf.general.dpi, ...
                "nbins", nbins_pdf, ...
                "Norm", "pdf", ...
                "FaceColor", graf.general.face_color, ...
                "XLabel", Etiq_x, ...
                "YLabel", Etiq_y, ...
                "Limx", graf.(variable).pdf.Limx, ...
                "Limy", graf.(variable).pdf.Limy, ...
                "XTick", graf.(variable).pdf.XTick, ...
                "YTick", graf.(variable).pdf.YTick, ...
                "Label_Leg", {}, ...
                "N_c", 1, ...
                "Font", graf.general.font, ...
                "Back_Col", graf.general.back_col, ...
                "TFax", graf.general.TFax, ...
                "TFLabel", graf.general.TFLabel, ...
                "TWax", graf.general.TWax, ...
                "TWLabel", graf.general.TWLabel, ...
                "Grid", graf.general.grid_pdf, ...
                "Text", Text, ...
                "units", "centimeters", ...
                "visible", graf.general.visible, ...
                "W", graf.general.W, ...
                "H", graf.general.H, ...
                "Of_W", graf.general.Of_W, ...
                "Of_H", graf.general.Of_H);
        end
    end
end

%% Funciones de distribución acumulada mensuales

if opts.do_cdf_mensual
    nombre_fig = ['CDF_mensual_', char(variable), '_'];
    
    for m = 1:12

        mes = get_month_name(month_names, m);
        var = datos_procesados.params(nodo).(variable).(mes);
        var = clean_vector(var);

        if isempty(var)
            print_skip(opts.disp_info, 'CDF mensual', variable, mes);
            continue
        end
    
        [f1, x1] = ecdf(var);
        [x_q, y_q, Text] = cdf_quantiles(var, ...
                                        unidad, ...
                                        graf.(variable).cdf, ...
                                        graf.(variable).cdf.TextSize);

        N_fig = [[nombre_fig, nombre], mes];
        Etiq_x = [char(variable), ' (', char(unidad), ')'];
        Etiq_y = 'Probabilidad acumulada';
    
        Est_Lineas = {'b,-,1,none,1.5,k,k','#9b9b9b,--,0.7,none,1.5,k,k'};
    
        IM_plot_2D({x1, x_q}, {f1, y_q}, ...
            "Name", N_fig, ...
            "titulo", "", ...
            "ext", graf.general.ext, ...
            "save_dir", save_dir_fig, ...
            "dpi", graf.general.dpi, ...
            "XLabel", Etiq_x, ...
            "YLabel", Etiq_y, ...
            "Limx", graf.(variable).cdf.Limx, ...
            "Limy", graf.(variable).cdf.Limy, ...
            "XTick", graf.(variable).cdf.XTick, ...
            "YTick", graf.(variable).cdf.YTick, ...
            "Label_Leg", {}, ...
            "N_c", 1, ...
            "Font", graf.general.font, ...
            "Back_Col", graf.general.back_col, ...
            "TFax", 11, ...
            "TFLabel", 11, ...
            "TWax", graf.general.TWax, ...
            "TWLabel", graf.general.TWLabel, ...
            "Style_Line", Est_Lineas, ...
            "Grid", graf.general.grid_cdf, ...
            "Text", Text, ...
            "units", "centimeters", ...
            "visible", graf.general.visible, ...
            "W", graf.general.W, ...
            "H", graf.general.H, ...
            "Of_W", graf.general.Of_W, ...
            "Of_H", graf.general.Of_H);
    end
end
    
%% Rosas mensuales
if opts.do_rose_mensual
    nombre_fig = ['Rosa_mensual_', char(variable), '_'];
    
    for m = 1:12
        mes = get_month_name(month_names, m);
        var = datos_procesados.params(nodo).(variable).(mes);
        Dir = datos_procesados.params(nodo).(direccion_variable).(mes);
        [var, Dir] = clean_pair(var, Dir);

        if isempty(var)
            print_skip(opts.disp_info, 'Rosa mensual', variable, mes);
            continue
        end
    
        N_fig = [[nombre_fig, nombre], month_names{m}];
    
        IM_plot_rose(Dir, var, ...
            "Name", N_fig, ...
            "ext", graf.general.ext, ...
            "dpi", graf.general.dpi, ...
            "titulo", "", ...
            "legenvar", variable, ...
            "legenbar", ['Magnitud de ', char(variable), ' [', char(unidad), ']'], ...
            "font", 14, ...
            "textfont", graf.general.font, ...
            "color", "k", ...
            "ndir", graf.(variable).rose.ndir, ...
            "cmap", "jet", ...
            "mag_bar", graf.(variable).rose.mag_bar, ...
            "legendtype", 2, ...
            "positionlegend", "bestoutside", ...
            "gridstyle", "--", ...
            "gridalpha", 0.35, ...
            "maxq", graf.(variable).rose.maxq, ...
            "griddiv", graf.(variable).rose.griddiv, ...
            "freqangle", graf.(variable).rose.freqangle, ...
            "rad", graf.(variable).rose.rad, ...
            "W", 20, ...
            "H", 20, ...
            "save_dir", save_dir_fig);
    end
end
    
    
    
%% PDF, CDF y rosas estacionales

if opts.do_estacional  

    for s = 1:numel(seasons)

        season = seasons(s);
        season_name = season_label.(season);
    
        var_raw = datos_procesados.params(nodo).(variable).(season);
        Dir_raw = datos_procesados.params(nodo).(direccion_variable).(season);
    
        var = clean_vector(var_raw);
        [var_rose, Dir_rose] = clean_pair(var_raw, Dir_raw);

        if isempty(var)
            print_skip(opts.disp_info, 'Gráficos estacionales', variable, season);
            continue
        end

        %% PDF estacional

        nombre_fig = ['PDF_', char(season_name), '_', char(variable)];
        N_fig = [nombre_fig, nombre];
        Etiq_x = [char(variable), ' (', char(unidad), ')'];
        Etiq_y = 'Densidad de probabilidad';
    
        Text = stat_text_pdf(var, ...
                        unidad, ...
                        graf.(variable).pdf.TextX, ...
                        graf.(variable).pdf.TextY, ...
                        graf.(variable).pdf.TextStep, ...
                        graf.(variable).pdf.TextSize);

        IM_plot_histogram(var, ...
            "Name", N_fig, ...
            "titulo", "", ...
            "ext", graf.general.ext, ...
            "save_dir", save_dir_fig, ...
            "dpi", graf.general.dpi, ...
            "nbins", nbins_pdf, ...
            "Norm", "pdf", ...
            "FaceColor", graf.general.face_color, ...
            "XLabel", Etiq_x, ...
            "YLabel", Etiq_y, ...
            "Limx", graf.(variable).pdf.Limx, ...
            "Limy", graf.(variable).pdf.Limy, ...
            "XTick", graf.(variable).pdf.XTick, ...
            "YTick", graf.(variable).pdf.YTick, ...
            "Label_Leg", {}, ...
            "N_c", 1, ...
            "Font", graf.general.font, ...
            "Back_Col", graf.general.back_col, ...
            "TFax", graf.general.TFax, ...
            "TFLabel", graf.general.TFLabel, ...
            "TWax", graf.general.TWax, ...
            "TWLabel", graf.general.TWLabel, ...
            "Grid", graf.general.grid_pdf, ...
            "Text", Text, ...
            "units", "centimeters", ...
            "visible", graf.general.visible, ...
            "W", graf.general.W, ...
            "H", graf.general.H, ...
            "Of_W", graf.general.Of_W, ...
            "Of_H", graf.general.Of_H);
    
    
        %% CDF estacional
    
        nombre_fig = ['CDF_', char(season_name), '_', char(variable)];
        N_fig = [nombre_fig, nombre];
    
        Etiq_x = [char(variable), ' (', char(unidad), ')'];
        Etiq_y = 'Probabilidad acumulada';
    
        [f1, x1] = ecdf(var);
        [x_q, y_q, Text] = cdf_quantiles(var, ...
                                        unidad, ...
                                        graf.(variable).cdf, ...
                                        graf.(variable).cdf.TextSize);
    
        Est_Lineas = {'b,-,1,none,1.5,k,k','#9b9b9b,--,0.7,none,1.5,k,k'};
    
        IM_plot_2D({x1, x_q}, {f1, y_q}, ...
            "Name", N_fig, ...
            "titulo", "", ...
            "ext", graf.general.ext, ...
            "save_dir", save_dir_fig, ...
            "dpi", graf.general.dpi, ...
            "XLabel", Etiq_x, ...
            "YLabel", Etiq_y, ...
            "Limx", graf.(variable).cdf.Limx, ...
            "Limy", graf.(variable).cdf.Limy, ...
            "XTick", graf.(variable).cdf.XTick, ...
            "YTick", graf.(variable).cdf.YTick, ...
            "Label_Leg", {}, ...
            "N_c", 1, ...
            "Font", graf.general.font, ...
            "Back_Col", graf.general.back_col, ...
            "TFax", 11, ...
            "TFLabel", 11, ...
            "TWax", graf.general.TWax, ...
            "TWLabel", graf.general.TWLabel, ...
            "Style_Line", Est_Lineas, ...
            "Grid", graf.general.grid_cdf, ...
            "Text", Text, ...
            "units", "centimeters", ...
            "visible", graf.general.visible, ...
            "W", graf.general.W, ...
            "H", graf.general.H, ...
            "Of_W", graf.general.Of_W, ...
            "Of_H", graf.general.Of_H);
    
    
        %% Rosa estacional

        if isempty(var_rose)
            print_skip(opts.disp_info, 'Rosa estacional', variable, season);
            continue
        end
    
        nombre_fig = ['Rosa_', char(season_name), '_', char(variable)];
        N_fig = [nombre_fig, nombre];
    
        IM_plot_rose(Dir_rose, var_rose, ...
            "Name", N_fig, ...
            "ext", graf.general.ext, ...
            "dpi", graf.general.dpi, ...
            "titulo", "", ...
            "legenvar", variable, ...
            "legenbar", ['Magnitud de ', char(variable), ' [', char(unidad), ']'], ...
            "font", 14, ...
            "textfont", graf.general.font, ...
            "color", "k", ...
            "ndir", graf.(variable).rose.ndir, ...
            "cmap", "jet", ...
            "mag_bar", graf.(variable).rose.mag_bar, ...
            "legendtype", 2, ...
            "positionlegend", "bestoutside", ...
            "gridstyle", "--", ...
            "gridalpha", 0.35, ...
            "maxq", graf.(variable).rose.maxq, ...
            "griddiv", graf.(variable).rose.griddiv, ...
            "freqangle", graf.(variable).rose.freqangle, ...
            "rad", graf.(variable).rose.rad, ...
            "W", 20, ...
            "H", 20, ...
            "save_dir", save_dir_fig);
    
    end

end

end