function [x_q, y_q, Text] = cdf_quantiles(var, unidad, graf_cdf, font_text)
    Qn1 = [0.25, 0.50, 0.85, 0.95, 0.99];
    Q1 = quantile(var, Qn1);

    x_q = [0,Q1(1),Q1(1),NaN, ...
           0,Q1(2),Q1(2),NaN, ...
           0,Q1(3),Q1(3),NaN, ...
           0,Q1(4),Q1(4),NaN, ...
           0,Q1(5),Q1(5)];

    y_q = [Qn1(1),Qn1(1),0,NaN, ...
           Qn1(2),Qn1(2),0,NaN, ...
           Qn1(3),Qn1(3),0,NaN, ...
           Qn1(4),Qn1(4),0,NaN, ...
           Qn1(5),Qn1(5),0];

    x_fix = graf_cdf.TextX;
    y_fix = graf_cdf.TextY;
    step = graf_cdf.TextStep;

    Text = {{x_fix,y_fix,['Q(25%): ',num2str(Q1(1),'%.2f'),' ',char(unidad)],'k',font_text}, ...
            {x_fix,y_fix-step,['Q(50%): ',num2str(Q1(2),'%.2f'),' ',char(unidad)],'k',font_text}, ...
            {x_fix,y_fix-2*step,['Q(85%): ',num2str(Q1(3),'%.2f'),' ',char(unidad)],'k',font_text}, ...
            {x_fix,y_fix-3*step,['Q(95%): ',num2str(Q1(4),'%.2f'),' ',char(unidad)],'k',font_text}, ...
            {x_fix,y_fix-4*step,['Q(99%): ',num2str(Q1(5),'%.2f'),' ',char(unidad)],'k',font_text}};
end